version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      rollup-plugins:
        patterns:
          - "@rollup/*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      minor-patch:
        update-types: ["minor", "patch"]
